# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-17 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='姓名')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='定价')),
            ],
        ),
    ]
