# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-17 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_bookstore_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstore',
            name='desc',
        ),
    ]
